language: node_js
node_js:
  - "8.9.4"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libcairo2-dev
      - libjpeg-dev
      - libpango1.0-dev
      - libgif-dev
      - build-essential
      - g++
